language = "C++"
cpp_compat = true
namespace = "swc"
documentation = true

[parse]
parse_deps = false
include = ["swc"]

[export]
include = ["compile_file", "transpile", "transpile_file", "free_string"]

#[layout]
#aligned_pod = true
#
#[fn]
#sort_by = "Name"
#rename_args = "CamelCase"